import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="text-base">
                <p className="pb-6">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean convallis sapien at facilisis rutrum.
                    In ullamcorper convallis diam eu aliquet. Quisque aliquet augue non tellus aliquet volutpat. Donec
                    ac justo eu mauris convallis varius. Mauris accumsan ante non efficitur dictum. Maecenas varius dui
                    augue, ornare egestas lectus suscipit at. Integer blandit eu quam a vulputate. In ultrices
                    pellentesque arcu ut sagittis. Fusce non elit euismod, auctor velit gravida, faucibus nulla. Aenean
                    elementum ultricies erat, vel condimentum metus eleifend ac. Nunc et bibendum tellus, sit amet
                    mollis sem. Proin congue ante velit, et faucibus leo facilisis quis. Quisque fermentum elit non nunc
                    cursus, a scelerisque erat porta. Vestibulum ac pharetra massa.</p>

                <p className="pb-6">Donec ac est vel diam dapibus efficitur. Fusce ullamcorper pharetra enim, ac laoreet turpis fermentum
                    accumsan. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis
                    egestas. Integer suscipit mattis suscipit. Integer scelerisque enim nisl, in rutrum ipsum iaculis
                    ac. Ut dui orci, sodales non rhoncus in, dapibus id purus. Nullam blandit porta magna vel maximus.
                    Nullam laoreet, ipsum vitae scelerisque pellentesque, sapien diam gravida mi, eget eleifend ligula
                    velit id lectus. Nunc rhoncus hendrerit erat, fermentum lobortis orci. Donec gravida maximus
                    rhoncus. Curabitur id pulvinar nunc, vel tempus est. Aliquam aliquam neque et blandit tincidunt.
                    Quisque a porta diam.</p>

                <p className="pb-6">Vestibulum sodales rhoncus odio, sit amet venenatis lectus. Suspendisse semper dapibus libero, id
                    luctus ante porta fringilla. Sed ante enim, congue et blandit vitae, sodales ut tortor. Morbi sit
                    amet convallis ante, in pellentesque urna. Vivamus maximus sapien ut vulputate porttitor.
                    Suspendisse maximus mattis feugiat. In vel mi non dolor tincidunt porttitor non sed metus. Quisque
                    non congue turpis, at blandit lacus. Duis accumsan mi ante, id congue nibh imperdiet a. Suspendisse
                    justo augue, scelerisque quis finibus quis, feugiat at massa. Maecenas lacinia, diam a sollicitudin
                    vulputate, lacus lacus blandit ligula, vel mattis ante justo quis lorem.</p>

                <p className="pb-6">Nam vehicula nulla eget nisl interdum pellentesque. Sed ut pulvinar odio, ut dictum neque. Sed
                    bibendum at lorem in dapibus. Nullam sollicitudin ac sem at eleifend. Ut non sem feugiat felis
                    consectetur rhoncus non at eros. Suspendisse volutpat, velit ut aliquam tincidunt, libero ante
                    blandit ligula, ut accumsan leo lectus eget nibh. Vestibulum mattis, tortor non efficitur porta,
                    neque dui tincidunt quam, a efficitur metus ipsum quis ante. Aliquam in ex non ligula molestie
                    commodo. Vivamus placerat a risus vel pharetra. Nulla at nisi id elit cursus tincidunt ut non leo.
                    Duis eu arcu sed neque placerat dignissim. Mauris dapibus suscipit mattis. Sed porttitor malesuada
                    tortor non pellentesque. Donec orci erat, scelerisque efficitur lacus viverra, ultrices tristique
                    nulla.</p>

                <p>Morbi luctus feugiat ligula. Curabitur eget hendrerit elit. Sed consectetur urna nec efficitur
                    aliquet. Sed viverra dapibus ante, nec gravida tortor porttitor nec. Sed metus orci, eleifend sed
                    gravida vel, dictum nec purus. Curabitur et ipsum in turpis mattis tempor nec eget diam. Vestibulum
                    ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam imperdiet in magna
                    et condimentum. Sed tempus malesuada augue sed vulputate. Fusce pulvinar nec sem eget facilisis.
                    Vestibulum risus diam, sagittis vitae nunc vel, iaculis condimentum ante. Nam suscipit, turpis non
                    eleifend imperdiet, risus mauris tincidunt metus, eu blandit tortor odio interdum enim. Pellentesque
                    bibendum ligula ac dolor condimentum, eu scelerisque lacus blandit.</p>
            </div>
        </>
    )
}